name: AUR Release

on:
  push:
  #   tags:
  #     - "v*.*.*"
  # workflow_run:
  #   workflows: ["build-and-release"]
  #   types: 
  #     - completed


jobs:
  release-aur:
    name: release aur
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Get PKGBUILD and .SRCINFO
        id: get_pkgbuild
        run: |
          curl -o PKGBUILD https://raw.githubusercontent.com/morrieinmaas/agent-cli/feat/aur-auto-release/pkg/PKGBUILD
          curl -o .SRCINFO https://raw.githubusercontent.com/morrieinmaas/agent-cli/feat/aur-auto-release/pkg/.SRCINFO
      - name: Gather data and rewrite PKGBUILD file
        id: gather_data_and_rewrite
        run: |
          # sudo apt-get update 
          # sudo apt-get upgrade
          VERSION=$(curl --silent https://api.github.com/repos/animo/agent-cli/releases | jq '.[0]' |  jq -r .tag_name)
          # strip the v prefix
          VERSION=${VERSION:1}
          # replace package version in PKGBUILD
          sed -i '3s|.*|pkgver\='"$VERSION"'|' PKGBUILD
          # replace package version in .SRCINFO
          sed -i '3s|.*|        pkgver = '$VERSION'|' .SRCINFO
      - name: commit to AUR
        id: commit_aur
        env:
          AUR_KEY: ${{secrets.AUR_KEY}}
        run: |
          # get the version
          # sudo apt-get install openssh-client
          VERSION=$(curl --silent https://api.github.com/repos/animo/agent-cli/releases | jq '.[0]' |  jq -r .tag_name)
          # use the rsa key for git
          mkdir ~/.ssh
          touch ~/.ssh/aur
          touch ~/.ssh/known_hosts
          touch ~/.ssh/authorized_keys
          eval $(ssh-agent -s)
          # ssh-add - ${{ secrets.AUR_KEY }}
          echo "$AUR_KEY" | base64 -d  > ~/.ssh/aur
          # sed -i -e '$a\' ~/.ssh/aur
          # ssh-keygen -f ~/.ssh/aur -y > ~/.ssh/aur.pub
          # set the ssh config for aur
          cat >> ~/.ssh/config<<EOF

          Host aur.archlinux.org
            IdentityFile ~/.ssh/aur
            User animosolutions
          EOF
          sudo chmod 400 /home/runner/.ssh/aur
          sudo chmod 400 ~/.ssh/aur
          chmod 400 /home/runner/.ssh/aur
          chmod -x-w ~/.ssh/aur
          sudo chmod -x-w ~/.ssh/aur
          chmod 400 ~/.ssh/aur
          sudo chmod 700 ~/.ssh
          #sudo chmod 600 ~/.ssh/authorized_keys
          #sudo chmod 600 ~/.ssh/known_hosts
          sudo service ssh restart
          eval $(ssh-agent)
          ssh-add ~/.ssh/aur
          sudo chmod 400 /home/runner/.ssh/aur
          sudo chmod 400 ~/.ssh/aur
          chmod 400 /home/runner/.ssh/aur
          chmod 400 ~/.ssh/aur
          # ssh-keygen -R aur.archlinux.org
          ssh-keyscan -t rsa aur.archlinux.org >> ~/.ssh/known_hosts
          # get the aur repo
          # ssh -vvv aur.archlinux.org
          git clone ssh://aur@aur.archlinux.org/agent-cli.git
          cd agent-cli
          # # set git username and email
          git config user.name "animosolutions"
          git config user.email "contact@animo.id"
          # git pull
          # # overwrite with the new files
          cp ../PKGBUILD PKGBUILD
          cp ../.SRCINFO .SRCINFO
          # # commit
          git commit -am "Release new agent-cli version ${VERSION}"
          # # add the remote
          git remote add aur ssh://aur@aur.archlinux.org/agent-cli.git
          # # push it
          # cat ~/.ssh/aur
          git push aur
        # env:
        #   AUR_KEY: ${{secrets.AUR_KEY}}
